
# Plant care data for 30 commonly grown plants
# Categories: Houseplants, Flowers, Fruits, Vegetables, Herbs

PLANTS = {

    # -- HOUSEPLANTS -----------------------------------------------------------

    "money plant": {
        "common_name":    "Money Plant",
        "scientific_name":"Epipremnum aureum",
        "category":       "Houseplant",
        "description":    "A popular indoor vine believed to bring good luck. Grows in soil or water.",
        "watering":       "Moderate — water when topsoil feels dry",
        "watering_every": "Once a week",
        "sunlight":       "Low to bright indirect light — avoid direct sun",
        "soil":           "Any well-drained potting mix",
        "pruning":        "Trim long vines anytime to keep it bushy",
        "temperature":    "15C to 35C",
        "maintenance":    "Very low",
        "growth_rate":    "Fast",
        "indoor":         True,
        "climates":       ["tropical", "subtropical", "temperate"]
    },
    "snake plant": {
        "common_name":    "Snake Plant",
        "scientific_name":"Sansevieria trifasciata",
        "category":       "Houseplant",
        "description":    "One of the hardiest houseplants. Tolerates low light and irregular watering.",
        "watering":       "Very low — only water when soil is completely dry",
        "watering_every": "Every 2-4 weeks",
        "sunlight":       "Low to bright indirect light",
        "soil":           "Sandy, well-draining soil or cactus mix",
        "pruning":        "Remove dead or damaged leaves at the base",
        "temperature":    "10C to 35C",
        "maintenance":    "Very low",
        "growth_rate":    "Slow",
        "indoor":         True,
        "climates":       ["tropical", "subtropical", "temperate", "cold"]
    },
    "pothos": {
        "common_name":    "Pothos",
        "scientific_name":"Epipremnum aureum",
        "category":       "Houseplant",
        "description":    "A trailing vine that thrives in almost any indoor condition. Great for beginners.",
        "watering":       "Moderate — water when top inch of soil is dry",
        "watering_every": "Every 1-2 weeks",
        "sunlight":       "Low to bright indirect light",
        "soil":           "Any standard potting mix",
        "pruning":        "Trim vines to control length and encourage fullness",
        "temperature":    "10C to 35C",
        "maintenance":    "Very low",
        "growth_rate":    "Fast",
        "indoor":         True,
        "climates":       ["tropical", "subtropical", "temperate", "cold"]
    },
    "lily": {
        "common_name":    "Lily",
        "scientific_name":"Spathiphyllum",
        "category":       "Houseplant",
        "description":    "An elegant indoor plant with white flowers. One of the best air-purifying plants.",
        "watering":       "Moderate — water when leaves slightly droop or soil is dry",
        "watering_every": "Once a week",
        "sunlight":       "Low to medium indirect light — avoid direct sun",
        "soil":           "Moist, well-drained potting mix",
        "pruning":        "Remove yellow leaves and spent flowers at the base",
        "temperature":    "15C to 30C",
        "maintenance":    "Low",
        "growth_rate":    "Moderate",
        "indoor":         True,
        "climates":       ["tropical", "subtropical", "temperate"]
    },
    "aloe vera": {
        "common_name":    "Aloe Vera",
        "scientific_name":"Aloe barbadensis miller",
        "category":       "Houseplant",
        "description":    "A succulent with thick gel-filled leaves. Useful for skin and burns. Very easy to grow.",
        "watering":       "Minimal — let soil dry out completely between waterings",
        "watering_every": "Every 2-3 weeks",
        "sunlight":       "Bright indirect sunlight or partial sun",
        "soil":           "Sandy or cactus mix — must drain very well",
        "pruning":        "No pruning needed — remove dead outer leaves only",
        "temperature":    "13C to 40C",
        "maintenance":    "Low",
        "growth_rate":    "Slow",
        "indoor":         True,
        "climates":       ["tropical", "dry", "subtropical"]
    },
    "spider plant": {
        "common_name":    "Spider Plant",
        "scientific_name":"Chlorophytum comosum",
        "category":       "Houseplant",
        "description":    "A cheerful plant with arching green and white striped leaves. Great air purifier.",
        "watering":       "Moderate — water when top inch of soil is dry",
        "watering_every": "Every 1-2 weeks",
        "sunlight":       "Bright indirect light",
        "soil":           "Well-drained all-purpose potting mix",
        "pruning":        "Remove brown tips and cut off baby plantlets to propagate",
        "temperature":    "10C to 30C",
        "maintenance":    "Low",
        "growth_rate":    "Fast",
        "indoor":         True,
        "climates":       ["temperate", "subtropical", "tropical"]
    },
    "cactus": {
        "common_name":    "Cactus",
        "scientific_name":"Cactaceae",
        "category":       "Houseplant",
        "description":    "A drought-tolerant plant perfect for dry, sunny spots. Needs almost no attention.",
        "watering":       "Very low — water only when soil is bone dry",
        "watering_every": "Every 2-4 weeks in summer, once a month in winter",
        "sunlight":       "Full sun — loves direct sunlight",
        "soil":           "Sandy cactus mix with excellent drainage",
        "pruning":        "No pruning needed",
        "temperature":    "10C to 45C",
        "maintenance":    "Very low",
        "growth_rate":    "Very slow",
        "indoor":         True,
        "climates":       ["dry", "tropical"]
    },

    # -- FLOWERS ---------------------------------------------------------------

    "rose": {
        "common_name":    "Rose",
        "scientific_name":"Rosa",
        "category":       "Flower",
        "description":    "A classic flowering plant loved for its fragrant blooms. Great for gardens and pots.",
        "watering":       "Regular — keep soil moist but not waterlogged",
        "watering_every": "Every 2-3 days in summer, once a week in winter",
        "sunlight":       "Full sun — at least 6 hours of direct sunlight daily",
        "soil":           "Well-drained, loamy soil rich in organic matter",
        "pruning":        "February and March — cut dead wood and shape the plant",
        "temperature":    "15C to 35C",
        "maintenance":    "Medium",
        "growth_rate":    "Moderate",
        "indoor":         False,
        "climates":       ["subtropical", "temperate"]
    },
    "marigold": {
        "common_name":    "Marigold",
        "scientific_name":"Tagetes",
        "category":       "Flower",
        "description":    "A bright, cheerful flower that also repels insects. Very easy to grow from seeds.",
        "watering":       "Moderate — water at the base, avoid wetting leaves",
        "watering_every": "Every 2-3 days",
        "sunlight":       "Full sun — at least 6 hours daily",
        "soil":           "Well-drained, moderately fertile soil",
        "pruning":        "Deadhead spent flowers regularly to encourage more blooms",
        "temperature":    "18C to 35C",
        "maintenance":    "Low",
        "growth_rate":    "Fast",
        "indoor":         False,
        "climates":       ["tropical", "subtropical", "temperate"]
    },
    "hibiscus": {
        "common_name":    "Hibiscus",
        "scientific_name":"Hibiscus rosa-sinensis",
        "category":       "Flower",
        "description":    "A tropical flowering shrub with large, vibrant blooms. Very popular in Indian gardens.",
        "watering":       "Regular — keep soil consistently moist",
        "watering_every": "Daily in summer, every 2 days in cooler months",
        "sunlight":       "Full sun — needs 6+ hours of direct sun",
        "soil":           "Well-drained, slightly acidic fertile soil",
        "pruning":        "Prune after flowering to shape and encourage new growth",
        "temperature":    "20C to 40C",
        "maintenance":    "Medium",
        "growth_rate":    "Fast",
        "indoor":         False,
        "climates":       ["tropical", "subtropical"]
    },
    "jasmine": {
        "common_name":    "Jasmine",
        "scientific_name":"Jasminum",
        "category":       "Flower",
        "description":    "A climbing plant with intensely fragrant white flowers. Very popular in South Asian homes.",
        "watering":       "Regular — water deeply but allow soil to dry slightly between waterings",
        "watering_every": "Every 2-3 days",
        "sunlight":       "Full sun to partial shade",
        "soil":           "Well-drained loamy soil",
        "pruning":        "Prune after flowering to keep shape and encourage growth",
        "temperature":    "15C to 35C",
        "maintenance":    "Medium",
        "growth_rate":    "Fast",
        "indoor":         False,
        "climates":       ["tropical", "subtropical"]
    },
    "lavender": {
        "common_name":    "Lavender",
        "scientific_name":"Lavandula",
        "category":       "Flower",
        "description":    "A fragrant herb with purple flowers. Known for calming properties and beautiful aroma.",
        "watering":       "Low — drought tolerant once established",
        "watering_every": "Every 1-2 weeks",
        "sunlight":       "Full sun — needs at least 6 hours",
        "soil":           "Sandy, alkaline, well-drained soil",
        "pruning":        "Prune after flowering in late summer",
        "temperature":    "5C to 30C",
        "maintenance":    "Low",
        "growth_rate":    "Moderate",
        "indoor":         False,
        "climates":       ["temperate", "dry"]
    },
    "sunflower": {
        "common_name":    "Sunflower",
        "scientific_name":"Helianthus annuus",
        "category":       "Flower",
        "description":    "A tall, cheerful flower that turns toward the sun. Easy to grow from seeds.",
        "watering":       "Moderate — water deeply but infrequently",
        "watering_every": "Every 3-4 days",
        "sunlight":       "Full sun — needs 6-8 hours of direct sunlight",
        "soil":           "Well-drained, slightly acidic to neutral soil",
        "pruning":        "Deadhead to encourage more blooms on branching varieties",
        "temperature":    "18C to 35C",
        "maintenance":    "Low",
        "growth_rate":    "Fast",
        "indoor":         False,
        "climates":       ["temperate", "subtropical", "dry"]
    },
    "bougainvillea": {
        "common_name":    "Bougainvillea",
        "scientific_name":"Bougainvillea spectabilis",
        "category":       "Flower",
        "description":    "A stunning climbing plant covered in bright papery flowers. Very common in Indian gardens.",
        "watering":       "Low to moderate — let soil dry between waterings",
        "watering_every": "Every 3-4 days in summer, less in winter",
        "sunlight":       "Full sun — needs at least 5 hours of direct sun",
        "soil":           "Well-drained, slightly acidic soil",
        "pruning":        "Prune after each flowering cycle to encourage new blooms",
        "temperature":    "20C to 40C",
        "maintenance":    "Low",
        "growth_rate":    "Fast",
        "indoor":         False,
        "climates":       ["tropical", "subtropical", "dry"]
    },
    "dahlia": {
        "common_name":    "Dahlia",
        "scientific_name":"Dahlia pinnata",
        "category":       "Flower",
        "description":    "A showstopping flower with large, complex blooms in many colors. Grown from tubers.",
        "watering":       "Regular — keep soil consistently moist",
        "watering_every": "Every 2-3 days",
        "sunlight":       "Full sun — 6-8 hours daily",
        "soil":           "Rich, well-drained soil with compost",
        "pruning":        "Pinch growing tips early and deadhead spent flowers regularly",
        "temperature":    "15C to 30C",
        "maintenance":    "Medium",
        "growth_rate":    "Moderate",
        "indoor":         False,
        "climates":       ["temperate", "subtropical"]
    },

    # -- FRUITS ----------------------------------------------------------------

    "tomato": {
        "common_name":    "Tomato",
        "scientific_name":"Solanum lycopersicum",
        "category":       "Fruit/Vegetable",
        "description":    "One of the most popular home-grown vegetables. Can be grown in pots or garden beds.",
        "watering":       "Regular — keep soil evenly moist",
        "watering_every": "Every 1-2 days in summer",
        "sunlight":       "Full sun — needs 8 hours of direct sunlight",
        "soil":           "Rich, fertile, well-drained soil",
        "pruning":        "Remove suckers (side shoots) regularly for better fruit yield",
        "temperature":    "18C to 35C",
        "maintenance":    "Medium",
        "growth_rate":    "Fast",
        "indoor":         False,
        "climates":       ["subtropical", "temperate", "tropical"]
    },
    "lemon": {
        "common_name":    "Lemon",
        "scientific_name":"Citrus limon",
        "category":       "Fruit",
        "description":    "A small citrus tree that can grow in pots. Gives fruit year-round in warm climates.",
        "watering":       "Regular — keep soil moist but never waterlogged",
        "watering_every": "Every 2-3 days",
        "sunlight":       "Full sun — at least 8 hours daily",
        "soil":           "Well-drained, slightly acidic soil",
        "pruning":        "Prune dead branches after fruiting to maintain shape",
        "temperature":    "15C to 38C",
        "maintenance":    "Medium",
        "growth_rate":    "Moderate",
        "indoor":         False,
        "climates":       ["tropical", "subtropical"]
    },
    "strawberry": {
        "common_name":    "Strawberry",
        "scientific_name":"Fragaria ananassa",
        "category":       "Fruit",
        "description":    "A sweet, compact fruit plant perfect for pots and balconies. Loved by everyone.",
        "watering":       "Regular — keep soil consistently moist",
        "watering_every": "Every 1-2 days",
        "sunlight":       "Full sun — 6-8 hours daily",
        "soil":           "Sandy loam with good drainage and slightly acidic pH",
        "pruning":        "Remove runners to focus energy on fruit production",
        "temperature":    "15C to 28C",
        "maintenance":    "Medium",
        "growth_rate":    "Moderate",
        "indoor":         False,
        "climates":       ["temperate", "subtropical"]
    },
    "guava": {
        "common_name":    "Guava",
        "scientific_name":"Psidium guajava",
        "category":       "Fruit",
        "description":    "A tropical fruit tree that grows well in Indian climates. Nutritious and easy to care for.",
        "watering":       "Moderate — water deeply but allow soil to dry between waterings",
        "watering_every": "Every 3-4 days",
        "sunlight":       "Full sun — at least 6 hours daily",
        "soil":           "Any well-drained soil — very adaptable",
        "pruning":        "Prune after harvest to control size and encourage new growth",
        "temperature":    "20C to 40C",
        "maintenance":    "Low",
        "growth_rate":    "Fast",
        "indoor":         False,
        "climates":       ["tropical", "subtropical"]
    },
    "chilli": {
        "common_name":    "Chilli",
        "scientific_name":"Capsicum annuum",
        "category":       "Fruit/Vegetable",
        "description":    "A spicy fruit plant that grows very well in Indian weather. Easy to grow in pots.",
        "watering":       "Moderate — keep soil moist but not soggy",
        "watering_every": "Every 2 days",
        "sunlight":       "Full sun — 6-8 hours daily",
        "soil":           "Well-drained fertile soil with compost",
        "pruning":        "Pinch growing tips to encourage bushy growth and more fruits",
        "temperature":    "20C to 38C",
        "maintenance":    "Low",
        "growth_rate":    "Moderate",
        "indoor":         False,
        "climates":       ["tropical", "subtropical"]
    },

    # -- VEGETABLES ------------------------------------------------------------

    "spinach": {
        "common_name":    "Spinach",
        "scientific_name":"Spinacia oleracea",
        "category":       "Vegetable",
        "description":    "A fast-growing leafy green rich in iron and vitamins. Great for kitchen gardens.",
        "watering":       "Regular — keep soil moist at all times",
        "watering_every": "Every day or every other day",
        "sunlight":       "Partial shade to full sun",
        "soil":           "Moist, nitrogen-rich fertile soil",
        "pruning":        "Harvest outer leaves regularly to encourage continuous growth",
        "temperature":    "10C to 24C",
        "maintenance":    "Low",
        "growth_rate":    "Fast",
        "indoor":         False,
        "climates":       ["temperate", "cold", "subtropical"]
    },
    "okra": {
        "common_name":    "Okra",
        "scientific_name":"Abelmoschus esculentus",
        "category":       "Vegetable",
        "description":    "Also called ladyfinger or bhindi. A heat-loving vegetable perfect for Indian summers.",
        "watering":       "Regular — water deeply 2-3 times a week",
        "watering_every": "Every 2-3 days",
        "sunlight":       "Full sun — needs 6-8 hours",
        "soil":           "Well-drained, fertile, slightly acidic soil",
        "pruning":        "Remove lower leaves to improve air circulation",
        "temperature":    "24C to 40C",
        "maintenance":    "Low",
        "growth_rate":    "Fast",
        "indoor":         False,
        "climates":       ["tropical", "subtropical"]
    },
    "cucumber": {
        "common_name":    "Cucumber",
        "scientific_name":"Cucumis sativus",
        "category":       "Vegetable",
        "description":    "A cooling vegetable that grows quickly in warm weather. Great for pots with a trellis.",
        "watering":       "Regular — keep soil consistently moist",
        "watering_every": "Every 1-2 days",
        "sunlight":       "Full sun — 6-8 hours daily",
        "soil":           "Well-drained, fertile, slightly acidic soil",
        "pruning":        "Pinch off growing tips once plant is established to encourage fruiting",
        "temperature":    "20C to 35C",
        "maintenance":    "Medium",
        "growth_rate":    "Fast",
        "indoor":         False,
        "climates":       ["tropical", "subtropical", "temperate"]
    },
    "carrot": {
        "common_name":    "Carrot",
        "scientific_name":"Daucus carota",
        "category":       "Vegetable",
        "description":    "A root vegetable that grows well in deep pots. Nutritious and satisfying to grow at home.",
        "watering":       "Regular — keep soil moist especially during germination",
        "watering_every": "Every 2-3 days",
        "sunlight":       "Full sun — at least 6 hours daily",
        "soil":           "Deep, loose, sandy soil free of stones",
        "pruning":        "Thin out seedlings to 5cm apart for proper root development",
        "temperature":    "10C to 25C",
        "maintenance":    "Low",
        "growth_rate":    "Moderate",
        "indoor":         False,
        "climates":       ["temperate", "cold", "subtropical"]
    },
    "brinjal": {
        "common_name":    "Brinjal",
        "scientific_name":"Solanum melongena",
        "category":       "Vegetable",
        "description":    "Also called eggplant or baingan. A staple vegetable in Indian cooking, easy to pot-grow.",
        "watering":       "Regular — keep soil evenly moist",
        "watering_every": "Every 2 days",
        "sunlight":       "Full sun — 6-8 hours daily",
        "soil":           "Rich, well-drained fertile soil",
        "pruning":        "Remove suckers and lower branches for better fruit production",
        "temperature":    "22C to 38C",
        "maintenance":    "Medium",
        "growth_rate":    "Moderate",
        "indoor":         False,
        "climates":       ["tropical", "subtropical"]
    },

    # -- HERBS -----------------------------------------------------------------

    "tulsi": {
        "common_name":    "Tulsi",
        "scientific_name":"Ocimum tenuiflorum",
        "category":       "Herb",
        "description":    "Also called Holy Basil. A sacred and medicinal herb widely grown in Indian homes.",
        "watering":       "Moderate — water when the top inch of soil feels dry",
        "watering_every": "Every 2-3 days",
        "sunlight":       "Full sun — needs 6-8 hours of sunlight",
        "soil":           "Well-drained fertile soil, slightly alkaline",
        "pruning":        "Pinch off flower buds regularly to encourage bushy growth",
        "temperature":    "20C to 40C",
        "maintenance":    "Low",
        "growth_rate":    "Fast",
        "indoor":         True,
        "climates":       ["tropical", "subtropical"]
    },
    "mint": {
        "common_name":    "Mint",
        "scientific_name":"Mentha",
        "category":       "Herb",
        "description":    "A fast-growing herb with a refreshing smell. Great for teas, cooking, and medicine.",
        "watering":       "Regular — keep soil consistently moist",
        "watering_every": "Every 1-2 days",
        "sunlight":       "Partial sun to full sun",
        "soil":           "Rich, moist, well-drained soil",
        "pruning":        "Pinch off tips regularly to prevent flowering and keep it bushy",
        "temperature":    "10C to 30C",
        "maintenance":    "Low",
        "growth_rate":    "Very fast",
        "indoor":         True,
        "climates":       ["temperate", "subtropical"]
    },
    "coriander": {
        "common_name":    "Coriander",
        "scientific_name":"Coriandrum sativum",
        "category":       "Herb",
        "description":    "Also called dhania. An essential kitchen herb used in almost every Indian dish.",
        "watering":       "Regular — keep soil moist but not waterlogged",
        "watering_every": "Every 1-2 days",
        "sunlight":       "Full sun to partial shade",
        "soil":           "Well-drained, fertile, loamy soil",
        "pruning":        "Harvest leaves regularly from the top to encourage more growth",
        "temperature":    "15C to 28C",
        "maintenance":    "Low",
        "growth_rate":    "Fast",
        "indoor":         True,
        "climates":       ["temperate", "subtropical"]
    },
    "curry leaf": {
        "common_name":    "Curry Leaf",
        "scientific_name":"Murraya koenigii",
        "category":       "Herb",
        "description":    "An essential Indian cooking herb. Grows as a small tree in warm climates.",
        "watering":       "Moderate — water when top inch of soil is dry",
        "watering_every": "Every 2-3 days",
        "sunlight":       "Full sun — at least 6 hours daily",
        "soil":           "Well-drained, loamy slightly acidic soil",
        "pruning":        "Prune young shoots to encourage bushy growth",
        "temperature":    "18C to 40C",
        "maintenance":    "Low",
        "growth_rate":    "Moderate",
        "indoor":         False,
        "climates":       ["tropical", "subtropical"]
    },
    "fenugreek": {
        "common_name":    "Fenugreek",
        "scientific_name":"Trigonella foenum-graecum",
        "category":       "Herb",
        "description":    "Also called methi. Leaves and seeds are used in Indian cooking. Very easy to grow.",
        "watering":       "Moderate — keep soil moist but not soggy",
        "watering_every": "Every 2 days",
        "sunlight":       "Full sun — 5-6 hours daily",
        "soil":           "Well-drained, sandy loam soil",
        "pruning":        "Harvest leaves regularly once the plant is 15cm tall",
        "temperature":    "10C to 30C",
        "maintenance":    "Very low",
        "growth_rate":    "Fast",
        "indoor":         True,
        "climates":       ["temperate", "subtropical", "cold"]
    },
    "basil": {
        "common_name":    "Basil",
        "scientific_name":"Ocimum basilicum",
        "category":       "Herb",
        "description":    "A fragrant culinary herb used in pastas, salads, and teas. Grows quickly in warm weather.",
        "watering":       "Regular — keep soil moist but not waterlogged",
        "watering_every": "Every 1-2 days",
        "sunlight":       "Full sun — 6-8 hours daily",
        "soil":           "Moist, well-drained, fertile soil",
        "pruning":        "Pinch off flower heads to keep leaves coming",
        "temperature":    "18C to 35C",
        "maintenance":    "Low",
        "growth_rate":    "Fast",
        "indoor":         True,
        "climates":       ["tropical", "subtropical", "temperate"]
    }
}

# Climate to suggested plants mapping
CLIMATE_PLANTS = {
    "tropical":    ["tulsi", "hibiscus", "aloe vera", "money plant", "jasmine"],
    "subtropical": ["rose", "marigold", "jasmine", "chilli", "lemon"],
    "temperate":   ["lavender", "mint", "spinach", "strawberry", "coriander"],
    "cold":        ["snake plant", "pothos", "fenugreek", "carrot", "spinach"],
    "dry":         ["cactus", "aloe vera", "bougainvillea", "lavender", "snake plant"]
}